### ISSUE TITLE
Implement depth-based occlusion

### ISSUE THREAD

**Issue by Foxinatel** [goudanough/WizARds#4]
Currently the quest is compositing the game world over the top of a passthrough layer.
This is a naive approach that results in the game world always appearing in front of the real world, so objects like the floor occlude the player's arms.
The quest 3 has support for a depth API (although it's not ratified into the Khronos OpenXR spec, so this will take a lot of API wrangling), but this will allow us to implement proper depth-based occlusion for a much more immersive experience.

**Comment by rosefromthedead** [comment]
working PoC in #19, but we just use the depth buffer as-is instead of accounting for head motion since the buffer was created. there's some linear algebra to do here, namely at the end of the fragment pipeline, unprojecting the fragment position and reprojecting it into the depth buffer's space, then we can do the depth comparison
